### ISSUE TITLE
Hello, I can't get this file according to the prompt, can you have other ways to provide the file, thank you very much

### ISSUE THREAD

**Issue by chuanfuye** [QZ-cmd/YOLOv3-TRT-jetson-nano#1]
wget https://raw.githubusercontent.com/pjreddie/darknet/f86901f6177dfc6116360a13cc06ab680e0c86b0/cfg/yolov3.cfg
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... 失败：拒绝连接。
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... 失败：拒绝连接。

**Comment by QZ-cmd** [comment]
> wget https://raw.githubusercontent.com/pjreddie/darknet/f86901f6177dfc6116360a13cc06ab680e0c86b0/cfg/yolov3.cfg
> 
> 正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
> 
> 正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... 失败：拒绝连接。
> 
> 正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... 失败：拒绝连接。


Maybe you can copy the URL directly to the downloader to download
